### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by tobiastom** [filamentgroup/criticalCSS#26]
World be nice to use a command line call like `criticalCSS http://github.com` which would just output the rules. This would it make it very easy to be integrated into all kinds of tools.

Thank you!

**Comment by jefflembeck** [comment]
So this is an option, however, our api would have to be something along the lines of:

`criticalCSS {url} {path/to/local/css/file/to/reference} {width} {height}`

I suppose the width and height could be options and could default to something if they're not filled in, but otherwise, the local css file and the url still need to be passed.

I'll look into having this library wrap a command-line version.

**Comment by tobiastom** [comment]
Thank you!

**Comment by LazerPanther** [comment]
+1

Would be amazing!

**Comment by jefflembeck** [comment]
Ok, this is in for version 0.6.0

**Comment by tobiastom** [comment]
Works like a charm! Thank you very much!

**Comment by nickcolley** [comment]
I was going to hit this! Nevermind, thanks a lot :) :tada:
