### ISSUE TITLE
Pseudo-elements' content entities are converted

### ISSUE THREAD

**Issue by goodguyry** [filamentgroup/criticalCSS#29]
Using criticalCSS via the Grunt task, I noticed entities in pseudo-elements' content property are being converted to their associated special characters and, thus, failing to render until the external CSS file has been parsed.

![screen shot 2015-03-27 at 5 34 00 pm](https://cloud.githubusercontent.com/assets/2059404/6879038/9a9933c2-d4a7-11e4-8406-a5e162f41de5.png)

Opening here because it doesn't seem particularly relevant to the Grunt task. Apologies if that's not the case. Let me know if you need additional information.

**Comment by zachleat** [comment]
Just repro’d this in a project so :+1: from me.

![image](https://cloud.githubusercontent.com/assets/39355/20715506/089cd126-b615-11e6-8fd9-033e9ff384e5.png)

turned into:
![image](https://cloud.githubusercontent.com/assets/39355/20715513/0e4eea8c-b615-11e6-8615-71d240a2512d.png)

I’d also vote to keep the single colon `:after` and `:before` too, since they have a little bit better browser compat but that nit is not a big deal.

**Comment by pacdemon** [comment]
Any progress on this bug?

**Comment by garygreen** [comment]
Wow, bug for 2 years? This is still a problem, just tried with CLI and fontawesome is getting converted. It should keep the value like `content: "\f002";`

![image](https://user-images.githubusercontent.com/1702638/28688702-a7fe8dd8-730a-11e7-8e60-02290ccf0988.png)

**Comment by Paul424** [comment]
Is there a workaround to this issue?

**Comment by roelal** [comment]
Unescaping and outputting as utf8 wouldn't be a problem. If only the quotes around it would be preserved.

For now, my workaround is using a regex-replace on the file afterwards. To place quotes around unquoted single-character `content:` strings in the unicode private use area that fontawesome seemingly uses:

search: `/(content:\s*)([\uf000-\uf300])(\s*;)/g`
replace: `'$1"$2"$3'`

**Comment by goodguyry** [comment]
I had a similar RegEx fix in place, but ultimately decided that was silly and switched to a different critical css package 🤐
